# Generated by Django 4.1.5 on 2025-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_snippet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='condition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='snippet',
            name='count',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='snippet',
            name='send_user',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
