# Generated by Django 4.1.5 on 2025-01-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_snippet_condition_snippet_count_snippet_send_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='code',
            new_name='text',
        ),
    ]
