# Generated by Django 4.1.5 on 2025-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_code_snippet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='status',
            field=models.CharField(default='Ожидается подтверждение', max_length=200),
        ),
    ]
