# Generated by Django 4.1.5 on 2025-02-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_snippet_user_repairrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ', max_length=200)),
                ('time_of_create', models.DateTimeField()),
                ('count', models.CharField(default='', max_length=200)),
                ('send_user', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
